[tools]
node = "lts"
rust = { version = "stable", profile = "minimal", components = "clippy,rustfmt" }
zizmor = "latest"

"cargo:cargo-deny" = "latest"
"cargo:cargo-mutants" = "latest"
"cargo:cargo-outdated" = "latest"
