---
name: Merge
"on":
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  labels:
    name: Labels
    runs-on: ubuntu-latest
    permissions:
      issues: write # required to read and write labels
      pull-requests: write # required to read and write labels

    steps:
      - uses: mheap/github-action-required-labels@0ac283b4e65c1fb28ce6079dea5546ceca98ccbe # v5.5
        with:
          mode: exactly
          count: 0
          labels: "S-do-not-merge, S-wip"
