---
name: Miri
"on":
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
  schedule:
    - cron: "0 0 * * WED"
jobs:
  miri:
    name: Test with Miri
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          components: miri, rust-src

      - name: Miri setup
        run: cargo miri setup

      - name: Miri test compile
        run: cargo miri test --no-run

      - name: Test unsafe code with Miri
        run: |
          cargo miri test --test leak_drop_symbol_table
          cargo miri test --test leak_drop_symbol_table_bytes
          cargo miri test --test leak_drop_symbol_table_cstr
          cargo miri test --test leak_drop_symbol_table_osstr
          cargo miri test --test leak_drop_symbol_table_path
