---
name: Miri
"on":
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
  schedule:
    - cron: "0 0 * * WED"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
permissions:
  contents: read # required to checkout repository
jobs:
  miri:
    name: Test with Miri
    runs-on: ubuntu-24.04
    env:
      RUST_BACKTRACE: 1
      MIRIFLAGS: "-Zmiri-strict-provenance -Zmiri-symbolic-alignment-check -Zrandomize-layout"

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Rust toolchain
        run: |
          rustup toolchain install nightly --profile minimal --component miri --component rust-src
          rustup default nightly

      - name: Miri setup
        run: cargo miri setup

      - name: Miri test compile
        run: cargo miri test --no-run

      - name: Test unsafe code with Miri
        run: cargo miri test --test leak_drop
