---
name: Miri
"on":
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
  schedule:
    - cron: "0 0 * * WED"
jobs:
  miri:
    name: Test with Miri
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
      MIRIFLAGS: "-Zmiri-strict-provenance -Zmiri-symbolic-alignment-check -Zrandomize-layout"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.0

      - name: Install Rust toolchain
        uses: artichoke/setup-rust/miri@v1.10.0
        with:
          toolchain: nightly

      - name: Miri setup
        run: cargo miri setup

      - name: Miri test compile
        run: cargo miri test --no-run

      - name: Test unsafe code with Miri
        run: cargo miri test --test leak_drop
